version: "3.9"

services:
  db:
    container_name: mon_db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - pmm-network

networks:
  pmm-network:
    external: true
